version: "3"

services:

    redis:

        image: "redis:6.2.1-alpine"

        container_name: redis

        ports:
          - "6379:6379"

    tarantool:

        image: "tarantool/tarantool:2.6.0"

        container_name: tarantool

        ports:
          - "3301:3301"

    reindexer:

        image: "reindexer/reindexer:v3.1.0"

        container_name: reindexer

        ports:
          - "9088:9088"
          - "6534:6534"